---
title: "ebolch_hw_8_pt1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Qian Ch. 6 Problem 4

```{r}
bod <- data.frame(Y = c(3.93, 6.8, 9.13, 10.86, 11.72, 12.58, 13.27, 14.23, 
	15.83, 16.81, 17.96, 18.45, 19.01, 19.58, 20.08, 20.49, NA, 
	22.46), Time = c(5, 10, 15, 20, 25, 30, 35, 40, 50, 60, 70, 80, 
	90, 100, 110, 120, 140, 180))
bod<- na.omit(bod)

plot(bod$Time,bod$Y)
```

## A 
For both of my models, I either have an error in the formulas or I need better starting values, which I'm pretty sure is the case. 

```{r}

# bod.m1 <- function(v,t){
#   L0 <- v[1]
#   N <- v[2]
#   k <- v[3]
#   f <-  L0-(L0^(1-N)-k*t*(1-N))^(1/(1-N))
#   return(f)}
# 
# bod.m<- nls(bod$Y ~ bod.m1(v,bod$Time), data = bod, start = list(v=c(1,2,
#                                                              0.5)))



```

## B

```{r}
# bod.m2 <- function(v,t){
#   L0 <- v[1]
#   k <- v[2]
#   f <- L0*(1-exp(-k*t))
#   return(f)}
# bod.m<- nls(Y ~ bod.m1(v,Time), data = bod, start = list(v=c(L0=0,
#                                                              k = 2)))

```

